using System.Collections.Generic;
using HSD.AudioBounce.Data;
using HSD.AudioBounce.Utilities;
using Unity.Collections;
using Unity.Jobs;
using UnityEngine;

using Color = System.Drawing.Color;

namespace HSD.AudioBounce.Main
{
    
    /// <summary>
    /// AudioBounce's ProbeDistributor is a component that distributes probes around the Character to detect 3D objects and calculate the reverb factor and occlusion factor for the audio sources in the scene.
    /// This could be entirely replaced by a custom implementation of the AB_Distributor class. You may want to do that for a Baked or a 2D solution.
    /// </summary>
    [AddComponentMenu("AudioBounce/Distributors/AB_ProbeDistributor")]
    public class AB_ProbeDistributor : AB_Distributor
    {
        [HideInInspector]
        public bool disable = false;
        
        public static AB_ProbeDistributor Instance;
        
        [Tooltip("The number of probes distributed around the character. The higher the number, the more accurate the probes distribution will be. However, this will also increase the number of raycasts and the processing time. PS: This is a debug value, it will be overwritten by the number of probes generated by the probes shape settings.")]
        public int numberOfProbes;

        [Header("Main Settings")]
        [Tooltip(
            "The number of frames that one cycle of update takes. 1 = EveryFrame (Faster but much heavier); 12 = The load is spread across 12 frames (Slower but much more performant). Let me tell you right now, you don't need it at 1, no game needs this to be that fast.")]
        // The number of frames over which to spread the raycasts
        public int framesToSpreadRaycasts = 12;

        [Tooltip(
            "This is the maximum reach of the 3D Environment scanning. Anything outside of this range will not be considered for occlusion and reverb adjustment. (It's probably going to sound very dim and quiet anyway)")]
        public float probesProjectionRadius = 25f;

        [Tooltip(
            "This is for offsetting the probes distribution Hit Points from the surface of the objects. This is useful for avoiding the probes to be placed inside the objects. It's recommended to keep this value as low as possible to avoid audio artifacts.")]
        public float hitPointNormalOffset = 0.25f;

        [Tooltip(
            "The layer mask to use for the raycasts projection for 3D objects detection. This should be set to the layer that your environment is on.")]
        public LayerMask layerMask = -1;

        private NativeArray<RaycastCommand>[] m_RaycastCommands;
        private NativeArray<RaycastHit>[] m_RaycastHits;
        private JobHandle[] m_JobHandles;

        [HideInInspector] public List<Vector3> preCastProbePositions = new List<Vector3>();

        
        //Probes Shape Settings
        [Header("Probes Shape Settings")]
        [Tooltip(
            "The number of points per row of the cylindrical probes distribution. The higher the number, the more accurate the probes distribution will be. However, this will also increase the number of raycasts and the processing load.")]
        public int numberOfPointsPerRow = 28;

        [Tooltip(
            "The number of rows of the cylindrical probes distribution. The higher the number, the more accurate the probes distribution will be. However, this will also increase the number of raycasts and the processing load.")]
        public int numberOfRows = 10;

        [Tooltip("The radius for each row of the cylindrical probes distribution.")]
        public float radius = 0.5f;

        [Tooltip("The total height of the cylindrical probes distribution.")]
        public float height = 0.75f;

        [Tooltip("The offset for the height of the cylindrical probes distribution.")]
        public float offset = 0f;

        [SerializeField]
        [Tooltip(
            "The height curve for the cylindrical probes distribution. This is useful to modulate the row distribution in height, allowing the user to have a more dense or sparse distribution in the selected points.")]
        public SharableCurve heightCurve;
        
        [SerializeField]
        [Tooltip(
            "Shrinking factor is useful to change the shape of the probes distribution structure by making the modulated rows smaller or bigger. This will affect the rays projection angle since the origin point is central to the component.")]
        public SharableCurve shrinkingFactor;
        
        [Tooltip(
            "This is useful to allow the shrinking factor to be reduced in order to avoid having shrunk rows with too many probes close to each other.")]
        public bool allowShrinkFactorReduction = true;

        [Tooltip(
            "This is the minimum number of probes the shrinking factor can reduce to. It limits how many probes can be removed from a single row.")]
        public int minimumShrinkNumberPerRow = 1;

        [Header("Debug Settings")] 
        public bool drawGizmos;
        [Tooltip("Draw the probes distribution before the raycasts are projected. Useful for editing the probes shape settings.")]
        public bool showPreCast;
        [Tooltip("Draw the probes distribution after the raycasts are projected. Useful for debugging the probes distribution position.")]
        public bool showPostCast;
        [Tooltip("If enabled will show the post cast points updating even in builds. Useful for debugging audio issues on playtests.")]
        public bool showPostCastOnBuild;
        [Tooltip("Draw a sphere with ray length of 'probesProjectionRadius'. Useful for debugging the probes distribution range.")]
        public bool showRayLength;


        
        private List<Vector3> m_PartialHitPoints = new List<Vector3>();
        [HideInInspector] public float totalRaycastDistanceTemp;
        [HideInInspector] public float totalRaycastDistance;
       
        private Vector3 m_TransformPosition;
        
#if UNITY_2022_2_OR_NEWER
        private QueryParameters m_Qp;
#endif
        private Dictionary<RaycastHit, float> m_HitAlphaMap = new Dictionary<RaycastHit, float>();
        private int m_StartCache = 0;
        private int m_EndCache = 0;
        private bool m_FirstRun = true;
        private int m_NumberOfProbesCache = 0;


        private void Awake()
        {
            if (Instance != null)
            {
                Destroy(this);
                return;
            }
            Instance = this;
        }


        private void Start()
        {
            GenerateCylindricalProbes(numberOfRows, numberOfPointsPerRow, radius, height, offset, heightCurve.curve,
                shrinkingFactor.curve);
            m_NumberOfProbesCache = numberOfProbes;
            m_RaycastCommands = new NativeArray<RaycastCommand>[1];
            m_RaycastHits = new NativeArray<RaycastHit>[1];
            m_JobHandles = new JobHandle[1];
            preCastProbePositions = new List<Vector3>(numberOfProbes);

            m_RaycastCommands[0] = new NativeArray<RaycastCommand>(numberOfProbes, Allocator.Persistent);
            m_RaycastHits[0] = new NativeArray<RaycastHit>(numberOfProbes, Allocator.Persistent);

        }

       
        public void Update()
        {
            if (disable)
                return;
            if(framesToSpreadRaycasts < 1)
                framesToSpreadRaycasts = 1;
            
            // Generate initial probes
            GenerateCylindricalProbes(numberOfRows, numberOfPointsPerRow, radius, height, offset, heightCurve.curve,
                shrinkingFactor.curve);
            
            // If the number of probes has changed, re-initialize the raycast arrays
            if (m_NumberOfProbesCache != numberOfProbes) 
            {
                m_RaycastCommands[0].Dispose();
                m_RaycastHits[0].Dispose();
                m_RaycastCommands[0] = new NativeArray<RaycastCommand>(numberOfProbes, Allocator.Persistent);
                m_RaycastHits[0] = new NativeArray<RaycastHit>(numberOfProbes, Allocator.Persistent);
                m_StartCache = 0;
                m_EndCache = 0;
                m_NumberOfProbesCache = numberOfProbes;
            }

            if (Time.frameCount % framesToSpreadRaycasts == 0)
            {
                // Only clear hitPoints at the start of the multi-frame cycle
                finalProbePosition.Clear(); 
                // Add the hit points from this frame to the overall list
                finalProbePosition.AddRange(m_PartialHitPoints); 
                // Clear temporary list as well as the total raycast distance
                m_PartialHitPoints.Clear(); 
                totalRaycastDistance = totalRaycastDistanceTemp;
                totalRaycastDistanceTemp = 0f;
                reverbFactor = CalculateReverbFactor();
            }

            if (!m_FirstRun)
            {
                // Process raycasts from last frame
                m_JobHandles[0].Complete();
                CacheRaycasts(m_StartCache, m_EndCache);
            }
            else
            {
                m_FirstRun = false;
            }

            int probesPerFrame = numberOfProbes / framesToSpreadRaycasts;
            int frameOffset = (Time.frameCount % framesToSpreadRaycasts) * probesPerFrame;
            int start = Mathf.Clamp(frameOffset, 0, numberOfProbes);
            int end = Mathf.Clamp(frameOffset + probesPerFrame, 0, numberOfProbes);
            m_StartCache = start;
            m_EndCache = end;

            // Update ray origins for the initial rays before any operations are done
            UpdateRaycastCommands(start, end);
            
            
            //SPECIAL GIZMOS CODE
            if(drawGizmos && showPostCast && showPostCastOnBuild)
                DrawBuildGizmos();
        }

        

        private void CacheRaycasts(int start, int end)
        {
            m_CurrentFrameHits.Clear();

            for (int j = start; j < end; j++)
            {
                RaycastHit hit = m_RaycastHits[0][j];

                //Calculate the total raycast distance
                if (hit.distance > 0f)
                {
                    totalRaycastDistanceTemp += hit.distance;
                }
                else
                {
                    // Calculate the maximum distance this raycast could travel
                    float maxRaycastDistance = probesProjectionRadius * 0.5f;
                    totalRaycastDistanceTemp += maxRaycastDistance;
                }

                if (hit.collider != null)
                {
                    // Add the hit points to the temporary list
                    m_PartialHitPoints.Add(hit.point + (hit.normal * hitPointNormalOffset));
                    
                    if (drawGizmos)
                        m_CurrentFrameHits.Add(hit); //GIZMO DEBUG LIST
                }
            }
        }

        public List<RaycastHit> m_CurrentFrameHits = new List<RaycastHit>();

        void UpdateRaycastCommands(int start, int end)
        {
            m_TransformPosition = transform.position;
            
#if UNITY_2022_2_OR_NEWER
            m_Qp.layerMask = layerMask;
#endif

            for (int i = start; i < end; i++)
            {
                // Retrieve the stored probe position
                Vector3 probePosition = preCastProbePositions[i];

                // Calculate the direction from the game object to the probe
                Vector3 direction = (probePosition - m_TransformPosition).normalized;

                // Create a new RaycastCommand with the updated direction
#if UNITY_2022_2_OR_NEWER
                m_RaycastCommands[0][i] = new RaycastCommand(m_TransformPosition, direction, m_Qp, probesProjectionRadius * 0.5f);
#else
                m_RaycastCommands[0][i] = new RaycastCommand(m_TransformPosition, direction,  probesProjectionRadius * 0.5f, layerMask);
#endif
               
            }
            m_JobHandles[0] = RaycastCommand.ScheduleBatch(m_RaycastCommands[0], m_RaycastHits[0], 1);
        }


        public override float CalculateReverbFactor()
        {
            // Calculate the maximum distance this raycast could travel
            float maxRaycastDistance = probesProjectionRadius * 0.5f;

            // Total distance is maxRaycastDistance times the number of probes
            float totalDistance = maxRaycastDistance * preCastProbePositions.Count;

            return (totalRaycastDistance / totalDistance);
        }


        void OnDestroy()
        {
            m_JobHandles[0].Complete();
            m_RaycastCommands[0].Dispose();
            m_RaycastHits[0].Dispose();
        }


        private void GenerateCylindricalProbes(int aNumberOfSlices, int aNumberOfPointsPerSlice, float aRadius, float aHeight,
            float offset, AnimationCurve heightCurve, AnimationCurve shrinkingCurve)
        {
            preCastProbePositions.Clear();
            var tr = transform;
            Vector3 pos = tr.position + tr.up * offset; // Apply the offset to the starting position
            Vector3 up = tr.up;

            for (int sliceIndex = 0; sliceIndex < aNumberOfSlices; sliceIndex++)
            {
                // Evaluate the height curve at the current slice index to calculate y-coordinate
                float t = sliceIndex / (float)(aNumberOfSlices - 1);
                float y = aHeight * heightCurve.Evaluate(t);

                // Calculate radius for current slice
                float sliceRadius = aRadius * shrinkingCurve.Evaluate(t);

                // Interpolate number of points for the current slice
                int pointsForThisSlice = Mathf.RoundToInt(aNumberOfPointsPerSlice * shrinkingCurve.Evaluate(t));
                if (allowShrinkFactorReduction)
                {
                    pointsForThisSlice =
                        Mathf.Max(pointsForThisSlice, minimumShrinkNumberPerRow); // Ensure at least 1 point
                }

                // Calculate angle step size
                float angleStep = 2 * Mathf.PI / pointsForThisSlice;

                for (int pointIndex = 0; pointIndex < pointsForThisSlice; pointIndex++)
                {
                    // Calculate angle
                    float angle = angleStep * pointIndex;

                    // Convert polar coordinates to Cartesian coordinates
                    float x = Mathf.Cos(angle) * sliceRadius;
                    float z = Mathf.Sin(angle) * sliceRadius;

                    // Store direction vector as probe position
                    Vector3 probePosition = pos + new Vector3(x, y, z);
                    probePosition += up * y; // Apply the offset directly related to the current slice height

                    // Add the probe position to the list
                    preCastProbePositions.Add(probePosition);
                }
            }

            numberOfProbes = preCastProbePositions.Count;
        }

        
        #region Gizmos
        private void DrawBuildGizmos()
        {
                foreach (var hit in m_CurrentFrameHits)
                {
                    nDebug.DrawPulseCube(hit.point + (hit.normal * hitPointNormalOffset), 0.16f, 0f, Color.DodgerBlue, Color.DimGray, 0.02f * framesToSpreadRaycasts, 1f, 0f);
                }
        }

        private void OnDrawGizmos()
        {
            if (!drawGizmos)
                return;

            if (showRayLength)
            {
                // Draw the initial sphere
                Gizmos.color = AB_Utilities.ToColor32(Color.Green);
                Gizmos.DrawWireSphere(transform.position, probesProjectionRadius * 0.5f);
            }

            if (showPreCast)
            {
                Gizmos.color = AB_Utilities.ToColor32(Color.Blue, 0.85f);
                foreach (Vector3 generatedPoint in preCastProbePositions)
                {
                    Gizmos.DrawSphere(generatedPoint, 0.05f);
                }
            }


            if (!showPostCastOnBuild)
                if (showPostCast)
                    DrawBuildGizmos();
              
        }
        #endregion
    }
}
